# 仅检索参考防御基线配置
# 仅使用检索到的真实图像作为参考，无生成模型

# 继承默认配置的基础设置
base_config: "default.yaml"

# 设备配置
device:
  primary: "cuda"
  fallback: "cpu"
  gpu_ids: [0, 1, 2, 3, 4, 5]
  memory_fraction: 0.8
  allow_growth: true

# 批处理配置
batch:
  default_size: 32
  max_size: 128
  min_size: 1
  auto_adjust: true

# 缓存配置
cache:
  enabled: true
  base_dir: "./data/cache"
  max_size: "50GB"
  ttl: 86400
  compression: true
  backends:
    features: "disk"
    images: "disk"
    indices: "disk"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./experiments/logs/baseline_retrieval_only.log"
  max_size: "100MB"
  backup_count: 5
  console: true

# 并行处理配置
parallel:
  max_workers: 8
  backend: "threading"
  chunk_size: "auto"

# 模型配置
models:
  # CLIP模型
  clip:
    default_model: "ViT-B/32"
    cache_dir: "./data/cache/models/clip"
    precision: "fp16"
    batch_size: 256
  
  # Qwen模型
  qwen:
    default_model: "Qwen/Qwen2-1.5B-Instruct"
    cache_dir: "./data/cache/models/qwen"
    precision: "fp16"
    max_length: 512
  
  # Stable Diffusion模型 - 禁用
  stable_diffusion:
    enabled: false
    default_model: "runwayml/stable-diffusion-v1-5"
    cache_dir: "./data/cache/models/sd"
    precision: "fp16"
    safety_checker: false

# 数据配置
data:
  base_dir: "./data"
  num_workers: 4
  pin_memory: true
  persistent_workers: true

# 实验配置
experiments:
  output_dir: "./experiments/results"
  save_intermediate: false
  reproducible: true
  seed: 42

# 防御配置 - 仅检索参考防御
defense:
  enabled: true
  method: "retrieval_reference_only"
  
  # 文本变体配置 - 使用语义一致生成
  text_variants:
    enabled: true
    method: "semantic_consistent"  # 使用语义一致生成方法
    num_variants: 5
    model: "qwen"
    strategies:
      - "paraphrase"        # 释义
      - "synonym_replace"   # 同义词替换
      - "structure_change"  # 句式变换
      - "detail_add"       # 细节补充
      - "perspective_shift" # 视角转换
    preserve_semantics: true
    quality_threshold: 0.8
  
  # 检索参考配置 - 启用
  retrieval_reference:
    enabled: true
    method: "faiss_search"
    top_k: 10
    similarity_threshold: 0.7
    index_type: "IVF"
    nprobe: 32
    use_gpu: true
    rerank: true
    diversity_factor: 0.3
  
  # 生成参考配置 - 禁用
  generative_reference:
    enabled: false
    num_generated: 0
    model: null
  
  # 一致性检测配置
  consistency_check:
    enabled: true
    method: "cross_modal_similarity"
    threshold: 0.65
    voting_strategy: "majority"
    weight_retrieval: 1.0
    weight_generative: 0.0  # 生成参考权重为0
    similarity_metrics:
      - "cosine"
      - "euclidean"
    aggregation: "weighted_average"
  
  # 自适应阈值
  adaptive_threshold:
    enabled: true
    method: "statistical"
    window_size: 100
    confidence_level: 0.95
    update_frequency: 10

# 攻击配置
attacks:
  pgd:
    enabled: true
    eps: 0.03
    alpha: 0.01
    steps: 10
  hubness:
    enabled: true
    k: 10
    alpha: 0.5
  fsta:
    enabled: true
    target_layer: "final"
    perturbation_budget: 0.03
  sma:
    enabled: true
    semantic_shift: 0.2

# 性能监控
monitoring:
  enabled: true
  gpu_memory: true
  cpu_usage: true
  disk_usage: true
  network: false

# 安全配置
security:
  allow_remote_code: false
  verify_ssl: true
  max_file_size: "1GB"

# 评估指标
metrics:
  attack_success_rate: true
  top_k_accuracy: true
  detection_accuracy: true
  false_positive_rate: true
  processing_time: true
  memory_usage: true
  retrieval_quality: true
  generative_quality: false