# 集成防御配置

# 防御策略配置
defense:
  name: "ensemble_defense"
  type: "multimodal_consistency"
  
  # 集成检测器配置
  ensemble:
    detectors: ["consistency", "similarity", "statistical"]
    weights: [0.3, 0.3, 0.4]
    voting_strategy: "weighted"  # "majority", "weighted", "unanimous"
    confidence_threshold: 0.5
    calibration_enabled: true
    
  # 一致性检测器
  consistency_detector:
    threshold: 0.8
    aggregation_method: "mean"  # "mean", "median", "max", "min"
    outlier_detection: true
    outlier_threshold: 2.0  # 标准差倍数
    min_variants: 5
    max_variants: 15
    
    # 一致性度量
    metrics:
      - "cosine_similarity"
      - "euclidean_distance"
      - "pearson_correlation"
    
    # 权重配置
    metric_weights: [0.5, 0.3, 0.2]
    
  # 相似度检测器
  similarity_detector:
    threshold: 0.85
    metric: "cosine"  # "cosine", "euclidean", "manhattan"
    reference_selection: "top_k"  # "top_k", "random", "diverse"
    num_references: 10
    
    # 参考库配置
    reference_bank:
      update_strategy: "fifo"  # "fifo", "lru", "random"
      max_size: 10000
      clustering_enabled: true
      num_clusters: 100
      
  # 统计检测器
  statistical_detector:
    method: "isolation_forest"  # "isolation_forest", "one_class_svm", "local_outlier_factor"
    contamination: 0.1
    n_estimators: 100
    random_state: 42
    
    # 特征提取
    feature_extraction:
      methods: ["clip_features", "statistical_features"]
      statistical_features:
        - "mean"
        - "std"
        - "skewness"
        - "kurtosis"
        - "entropy"
    
# 文本增强防御
text_augmentation:
  enabled: true
  num_variants: 10
  generation_strategy: "diverse"  # "diverse", "similar", "mixed"
  
  # 过滤策略
  filtering:
    similarity_range: [0.7, 0.95]
    remove_duplicates: true
    semantic_filtering: true
    
# 检索增强防御
retrieval_augmentation:
  enabled: true
  top_k: 20
  diversity_promotion: true
  
  # 检索策略
  strategy:
    multi_query: true
    query_expansion: true
    re_ranking: true
    
# SD参考生成防御
sd_reference_generation:
  enabled: true
  num_images_per_text: 3
  generation_diversity: 0.8
  
  # 生成策略
  strategy:
    prompt_engineering: true
    style_variation: true
    seed_variation: true
    
# 自适应防御
adaptive_defense:
  enabled: true
  
  # 威胁感知
  threat_detection:
    monitor_attack_patterns: true
    anomaly_threshold: 0.7
    adaptation_trigger: "confidence_drop"  # "confidence_drop", "pattern_change", "manual"
    
  # 参数调整
  parameter_adaptation:
    threshold_adjustment: true
    weight_rebalancing: true
    detector_selection: true
    adaptation_rate: 0.1
    
# 性能优化
optimization:
  # 缓存策略
  caching:
    enabled: true
    cache_text_features: true
    cache_image_features: true
    cache_similarities: true
    cache_ttl: 3600  # 秒
    
  # 并行处理
  parallel_processing:
    enabled: true
    max_workers: 4
    batch_processing: true
    async_processing: true
    
  # 模型优化
  model_optimization:
    mixed_precision: true
    torch_compile: true
    gradient_checkpointing: false
    
# 评估配置
evaluation:
  metrics:
    - "detection_accuracy"
    - "false_positive_rate"
    - "false_negative_rate"
    - "precision"
    - "recall"
    - "f1_score"
    - "auc_roc"
    - "processing_time"
    
  # 交叉验证
  cross_validation:
    enabled: true
    folds: 5
    stratified: true
    
  # 鲁棒性测试
  robustness_testing:
    noise_levels: [0.01, 0.03, 0.05, 0.1]
    attack_types: ["pgd", "fgsm", "c&w", "hubness"]
    
# 输出配置
output:
  save_detection_results: true
  save_intermediate_features: false
  save_statistics: true
  report_format: "json"  # "json", "yaml", "csv"
  
# 实验配置
experiment:
  name: "ensemble_defense_evaluation"
  num_runs: 5
  random_seed: 42
  reproducible: true
  
# 硬件配置
hardware:
  device: "cuda"
  mixed_precision: true
  compile_models: true
  memory_efficient: true
  
# 日志配置
logging:
  level: "INFO"
  log_detection_details: true
  log_performance_metrics: true
  save_logs: true
  log_interval: 50