# 全局默认配置
# 设备、batch、缓存、日志级别等基础设置

# 设备配置
device:
  primary: "cuda"  # 主设备
  fallback: "cpu"  # 备用设备
  gpu_ids: [0, 1, 2, 3, 4, 5]  # 可用GPU列表
  memory_fraction: 0.8  # GPU内存使用比例
  allow_growth: true  # 动态内存分配

# 批处理配置
batch:
  default_size: 32
  max_size: 128
  min_size: 1
  auto_adjust: true  # 根据GPU内存自动调整

# 缓存配置
cache:
  enabled: true
  base_dir: "./data/cache"
  max_size: "50GB"
  ttl: 86400  # 缓存过期时间(秒)
  compression: true
  backends:
    features: "disk"  # disk, memory, redis
    images: "disk"
    indices: "disk"

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./experiments/logs/app.log"
  max_size: "100MB"
  backup_count: 5
  console: true

# 并行处理配置
parallel:
  max_workers: 8
  backend: "threading"  # threading, multiprocessing
  chunk_size: "auto"

# 模型配置
models:
  # CLIP模型
  clip:
    default_model: "ViT-B/32"
    cache_dir: "./data/cache/models/clip"
    precision: "fp16"
    batch_size: 256
  
  # Qwen模型
  qwen:
    default_model: "Qwen/Qwen2-1.5B-Instruct"
    cache_dir: "./data/cache/models/qwen"
    precision: "fp16"
    max_length: 512
  
  # Stable Diffusion模型
  stable_diffusion:
    default_model: "runwayml/stable-diffusion-v1-5"
    cache_dir: "./data/cache/models/sd"
    precision: "fp16"
    safety_checker: false

# 数据配置
data:
  base_dir: "./data"
  num_workers: 4
  pin_memory: true
  persistent_workers: true

# 实验配置
experiments:
  output_dir: "./experiments/results"
  save_intermediate: false
  reproducible: true
  seed: 42

# 性能监控
monitoring:
  enabled: true
  gpu_memory: true
  cpu_usage: true
  disk_usage: true
  network: false

# 安全配置
security:
  allow_remote_code: false
  verify_ssl: true
  max_file_size: "1GB"